name: food_store_flutter
description: "food store flutter app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0-56.0.dev

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  retrofit: ^4.9.2
  logger: ^2.6.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  get_it: ^8.0.2
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^10.2.1
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  pretty_dio_logger: ^1.4.0
  flutter_lints: ^6.0.0
  flutter_dotenv: ^6.0.0
  auto_route_generator: ^10.4.0

targets:
  $default:
    builders:
      retrofit_generator:
        options:
          format_output: true
          auto_cast_response: true
          empty_request_body: false
          use_result: false

flutter:
  uses-material-design: true

  fonts:
    - family: BrandonGrotesque
      fonts:
        - asset: fonts/brandon_grotesque_thin.otf
          weight: 100
        - asset: fonts/brandon_grotesque_light.otf
          weight: 300
        - asset: fonts/brandon_grotesque_regular.otf
          weight: 400
        - asset: fonts/brandon_grotesque_medium.otf
          weight: 500
        - asset: fonts/brandon_grotesque_bold.otf
          weight: 700
    - family: BadScript
      fonts:
        - asset: fonts/bad_script_regular.ttf
          weight: 400


  assets:
    - assets/